Changed markup; cleaned scripts

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -4,18 +4,19 @@
 # get latest tag or current branch name if none
 TAG=`git describe --exact-match --abbrev=0 2>&1`
 if [[ `echo $TAG | grep fatal` != "" ]]; then
-    echo "No tag matches current HEAD. Create a tag to deploy."
-    exit 1
+    echo "No tag matches current HEAD. Using current branch..."
+    # This requires checking out the tag first?
+    TAG=`git branch | grep "*" | sed "s/* //"`
+    #exit 1
 fi
 
-# This requires checking out the tag first
-#TAG=$(git branch | grep "*" | sed "s/* //")
 echo "Deploying $TAG..."
 
-./minify
+# exit on error
+set -e
 
 git archive --format=tar HEAD | (mkdir -p /var/www/mognet-$TAG && tar -xf - -C /var/www/mognet-$TAG)
-rm -f /var/www/mognet && ln -s /var/www/mognet-$TAG /var/www/mognet
+rm -f /var/www/mognet ; ln -s /var/www/mognet-$TAG /var/www/mognet
 cd ..
 if [ ! -e /var/www/static ]; then
     ln -s "$(pwd)/static" /var/www/static  
@@ -24,16 +25,19 @@ if [ ! -e /var/www/res ]; then
     ln -s "$(pwd)/res" /var/www/res 
 fi
 cd - >/dev/null
-mkdir -p /var/www/log
-mkdir -p /var/www/mognet/data
 if [ -e app/node_modules ]; then
     cp -R app/node_modules /var/www/mognet/app
 fi
+
+mkdir -p /var/www/log
+mkdir -p /var/www/mognet/data
 chmod +x /var/www/mognet/deploy /var/www/mognet/reload /var/www/mognet/minify /var/www/mognet/app/bin/*.js
 
+echo "Minifying..."
+/var/www/mognet/minify
+
 echo "Updating index..."
-cd /var/www/mognet/app
 /var/www/mognet/app/bin/update.js >/dev/null
 
 echo "Deployed to /var/www/mognet-$TAG."
-echo "Start server with: npm start"
+echo "Start server with 'npm start' or redeploy with 'naught deploy'"
